# Generated by Django 5.1.15 on 2026-07-07 13:00

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(django.db.models.functions.text.Upper('email'), name='user_email_ci_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(django.db.models.functions.text.Upper('username'), name='user_username_ci_idx'),
        ),
    ]
