# Generated by Django 5.1.15 on 2026-07-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0005_user_avatar'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(condition=models.Q(('is_staff', False), ('is_verified', False)), fields=['created_at'], name='user_unverified_cleanup_idx'),
        ),
    ]
