# Generated by Django 5.1.15 on 2026-07-06 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['created_at']},
        ),
    ]
